### ISSUE TITLE
README_en.md may contain link to VGA -> SCART cable that may be unsuitable

### ISSUE THREAD

**Issue by janlavoie** [RndMnkIII/Analogizer#1]
Hi,

While reading through the README_en.md, I noticed a potential issue/inconsistency with the spanish version (README.md).

Specifically, in the section "What do you need to use it?" : 
After the explanation about VGA -> SCART, which mentions the recommendation for a particular cable because :

> It is recommended to use this cable with the Analogizer because it is verified that it takes the +5V from pin 9 of the VGA connector and passes it to pin 16 of the SCART

There is a list of links, 2 of them for VGA -> SCART cables : 

- https://manuferhi.com/p/cable-rgb-scart-for-mister-mist-sidi-and-n-go
- https://ultimatemister.com/product/rgb-scart-cable/
- (more links)

The second link (https://ultimatemister.com/product/rgb-scart-cable/) contains a cable which seems unsuitable based on the following information in the linked page : 

> - VGA pin 14 connects to SCART pin 16 directly (1,6v or less, no attenuation required) 
> - Our cable does not use VGA PIN 9, works with MiSTer I/O set in 3.3v 

When looking at the spanish README, that link in question is not present : 

> - https://manuferhi.com/p/cable-rgb-scart-for-mister-mist-sidi-and-n-go
> - https://antoniovillena.com/product/splitter-for-official-mister/
> - https://manuferhi.com/p/snac-adapter-for-mister
> - https://ultimatemister.com/product/snac-db15-neogeo/

The link in question was added exclusively to the english readme in the following changeset :  
https://github.com/RndMnkIII/Analogizer/commit/a6d653f981da6fd88093d54297811fb106a0b36a

---
Based on this, I believe this may have been a typo. I'm bringing it to your attention just in case it is indeed problematic.

Thank you very much for the work you are doing! Please accept my apologies if I misunderstood and am mistaken.
Best Regards,

**Comment by RndMnkIII** [comment]
VGA pin 14(VSync) is tied to high state in the Analogizer interface for RGBS video output or 3.3V. I think this should work with this cable.

**Comment by RndMnkIII** [comment]
VGA pin 14(VSync) is tied to high state in the Analogizer interface for RGBS video output or 3.3V. I think this should work with this cable.
