### ISSUE TITLE
Wrong reset state value for pin direction

### ISSUE THREAD

**Issue by rp-jt** [RndMnkIII/Analogizer#2]
Hello,
I was checking the module and found this:

https://github.com/RndMnkIII/Analogizer/blob/735b25853f16424eb71675a5ad0a6dd777965f87/analogizer/openFPGA_Pocket_Analogizer.v#L319

I think it doesn't make sense for it to be Z when reset or disabled. The pin direction at any point should be either 1 or 0, but it can't be Z.

**Comment by RndMnkIII** [comment]
Yes I know what you are saying, but in the end I have based myself on the value that Analogue recommends based on the template code they offer for developers, you can see the example here:
https://github.com/open-fpga/core-template/blob/main/src/fpga/core/core_top.v
```
// cart is unused, so set all level translators accordingly
// directions are 0:IN, 1:OUT
assign cart_tran_bank3 = 8'hzz;
assign cart_tran_bank3_dir = 1'b0;
assign cart_tran_bank2 = 8'hzz;
assign cart_tran_bank2_dir = 1'b0;
assign cart_tran_bank1 = 8'hzz;
assign cart_tran_bank1_dir = 1'b0;
assign cart_tran_bank0 = 4'hf;
assign cart_tran_bank0_dir = 1'b1;
assign cart_tran_pin30 = 1'b0;      // reset or cs2, we let the hw control it by itself
assign cart_tran_pin30_dir = 1'bz;
assign cart_pin30_pwroff_reset = 1'b0;  // hardware can control this
assign cart_tran_pin31 = 1'bz;      // input
assign cart_tran_pin31_dir = 1'b0;  // input
```
Maybe that pin30 is connected directly to the cartridge port? 
Related to this comment:
`// reset or cs2, we let the hw control it by itself` 

but, at the end the pin is defined in the module as output, yes is not sense:
`output  wire            cart_tran_pin30_dir,`
could be a typo, I don't know.

**Comment by RndMnkIII** [comment]
Fixed the code:
```	assign cart_tran_pin30         = i_rst | ~i_ena ? 1'bz : ((CART_PIN30_DIR) ? CART_PIN30_OUT : 1'bZ); //on reset state set ouput value to 4'hf
	assign cart_tran_pin30_dir     = i_rst | ~i_ena ? 1'b0 : CART_PIN30_DIR;                              //on reset state set pin dir to output
```
